# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-24 03:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profilepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='venueevents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_description', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('price', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='events',
            name='owner',
        ),
        migrations.DeleteModel(
            name='events',
        ),
    ]
