# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-26 03:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('profilepage', '0002_artistevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='artistlinks',
            fields=[
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='name_of_band', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
