# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-24 16:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0002_auto_20160424_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueevents',
            name='chosen',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chosen', to=settings.AUTH_USER_MODEL),
        ),
    ]
