# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splash', '0002_fulluser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fulluser',
            new_name='UserProfile',
        ),
    ]
