# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-21 03:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='connection',
            fields=[
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='target', to=settings.AUTH_USER_MODEL)),
                ('originator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='originator', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
