# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-21 22:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('displaypage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='originator',
        ),
        migrations.AddField(
            model_name='connection',
            name='originator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='originator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
