# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-21 03:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('displaypage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='originator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='originator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='connection',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='target', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
