# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-21 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displaypage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
