# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-21 03:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('displaypage', '0003_auto_20160421_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='originator',
        ),
        migrations.AddField(
            model_name='connection',
            name='originator',
            field=models.ManyToManyField(related_name='originator', to=settings.AUTH_USER_MODEL),
        ),
    ]
