# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-21 03:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('displaypage', '0005_auto_20160421_0344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='originator',
            new_name='start',
        ),
    ]
