# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-24 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepicture',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
