# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-11 00:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0004_auto_20160411_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='id',
        ),
        migrations.AlterField(
            model_name='description',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='band_name', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
