# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-11 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0006_auto_20160411_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='blurb',
            field=models.CharField(max_length=100),
        ),
    ]
