# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-14 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0007_auto_20160411_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepicture',
            field=models.ImageField(upload_to='propics'),
        ),
    ]
