# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-21 22:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('profilepage', '0008_auto_20160414_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='venue_name', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('event_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
