# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-23 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0009_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
