# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-24 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0011_auto_20160424_0207'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='event',
            new_name='events',
        ),
    ]
