# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-24 03:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0012_auto_20160424_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='numid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='venue_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
