# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-24 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilepage', '0015_auto_20160424_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='numid',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
